package com.github.wrdlbrnft.proguardannotations;

/**
 * Created by kapeller on 09/03/16.
 */
public enum KeepSetting {
    ALL,

    PUBLIC_CONSTRUCTORS,
    PROTECTED_CONSTRUCTORS,
    PACKAGE_LOCAL_CONSTRUCTORS,
    PRIVATE_CONSTRUCTORS,

    PUBLIC_INNER_CLASSES,
    PROTECTED_INNER_CLASSES,
    PACKAGE_LOCAL_INNER_CLASSES,
    PRIVATE_INNER_CLASSES,

    PUBLIC_MEMBERS,
    PROTECTED_MEMBERS,
    PACKAGE_LOCAL_MEMBERS,
    PRIVATE_MEMBERS,

    PUBLIC_METHODS,
    PROTECTED_METHODS,
    PACKAGE_LOCAL_METHODS,
    PRIVATE_METHODS,

    PUBLIC_FIELDS,
    PROTECTED_FIELDS,
    PACKAGE_LOCAL_FIELDS,
    PRIVATE_FIELDS
}
